# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=2083)),
                ('authors', models.ManyToManyField(to='biblio.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('editors', models.ManyToManyField(to='biblio.Author')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Publication'),
        ),
    ]
