# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0002_auto_20161002_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
