# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_content_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='cites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio.Content'),
        ),
    ]
