# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_content_cites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='cites',
        ),
        migrations.AddField(
            model_name='content',
            name='cites',
            field=models.ManyToManyField(blank=True, null=True, to='biblio.Content'),
        ),
    ]
