# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0005_auto_20161002_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblio.Organization')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='cites',
            field=models.ManyToManyField(blank=True, to='biblio.Content'),
        ),
        migrations.AddField(
            model_name='author',
            name='positions',
            field=models.ManyToManyField(to='biblio.Position'),
        ),
    ]
