# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_auto_20161003_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
