# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0011_auto_20161003_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
